
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ParserLexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int L_FLOAT = 49;
  public static final int L_STRING = 48;
  public static final int PARENTESISCIERRE = 8;
  public static final int CHAR = 15;
  public static final int FIN_EXPRESION = 9;
  public static final int CASE = 42;
  public static final int DIFERENTE = 33;
  public static final int CIERRACUENTO = 3;
  public static final int RESTA = 20;
  public static final int INTEGER = 13;
  public static final int DOS_PUNTOS = 46;
  public static final int FOR = 40;
  public static final int NEGATIVO = 27;
  public static final int ABREEMPAQUE = 4;
  public static final int IDENTIFICADOR = 18;
  public static final int IGUAL = 32;
  public static final int BOOL = 17;
  public static final int INCREMENTO = 25;
  public static final int ASIGNA = 6;
  public static final int SUMA = 19;
  public static final int IF = 37;
  public static final int MAIN = 12;
  public static final int EOF = 0;
  public static final int RETURN = 45;
  public static final int DECREMENTO = 26;
  public static final int error = 1;
  public static final int NEGACION = 36;
  public static final int MODULO = 23;
  public static final int ABRECUENTO = 2;
  public static final int MENOR = 28;
  public static final int BREAK = 44;
  public static final int PARENTESISAPERTURA = 7;
  public static final int CIERREEMPAQUE = 5;
  public static final int SWITCH = 41;
  public static final int MAYOR = 30;
  public static final int POTENCIA = 24;
  public static final int ELSE = 38;
  public static final int READ = 11;
  public static final int WHILE = 39;
  public static final int DEFAULT = 43;
  public static final int MAYOR_IGUAL = 31;
  public static final int FLOAT = 16;
  public static final int CONJUNCION = 34;
  public static final int STRING = 14;
  public static final int DISYUNCION = 35;
  public static final int MENOR_IGUAL = 29;
  public static final int DIVISION = 21;
  public static final int PRINT = 10;
  public static final int L_INTEGER = 47;
  public static final int MULTIPLICACION = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABRECUENTO",
  "CIERRACUENTO",
  "ABREEMPAQUE",
  "CIERREEMPAQUE",
  "ASIGNA",
  "PARENTESISAPERTURA",
  "PARENTESISCIERRE",
  "FIN_EXPRESION",
  "PRINT",
  "READ",
  "MAIN",
  "INTEGER",
  "STRING",
  "CHAR",
  "FLOAT",
  "BOOL",
  "IDENTIFICADOR",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICACION",
  "MODULO",
  "POTENCIA",
  "INCREMENTO",
  "DECREMENTO",
  "NEGATIVO",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "IGUAL",
  "DIFERENTE",
  "CONJUNCION",
  "DISYUNCION",
  "NEGACION",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "RETURN",
  "DOS_PUNTOS",
  "L_INTEGER",
  "L_STRING",
  "L_FLOAT"
  };
}

